theme: jekyll-theme-architect
title: [Lindsay Wesley Resume]
description: [Showcase of my experience and qualifiations for the Senior Product Manager - Experience Engineering Role]
content: [/here is my page]
